### ISSUE TITLE
Most pushes code around 00:00

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#101]
![h](http://i.fionn.live/dbdab5.png)

I mean, that doesn't make sense :)

**Comment by lowlighter** [comment]
It's based on the hour you have the most commits if I remember rightly 🙂 (if `config_timezone` is rightly set)

It was a bit to mimick WakaTime when I implemented it, like a "most active hour" but as people doesn't always commit when they're coding, I agree that these are not really revelant, especially since **habits** plugin got the charts features

**Comment by Milo123459** [comment]
All good, I made a PR btw. @lowlighter

**Comment by lowlighter** [comment]
I'm currently reading notifications but there's quite a few to unstack :P

**Comment by Milo123459** [comment]
👀
