### ISSUE TITLE
"Member of 0 organizations" when that clearly isn't the case 

### ISSUE THREAD

**Issue by LunarWatcher** [lowlighter/metrics#113]
The generated metrics results in the wrong number of organizations, as well as the wrong number of starred repos. (Community stats)

![image](https://user-images.githubusercontent.com/29489988/107131813-2fdb6a00-68da-11eb-8877-0f44b131e1b9.png)

**Comment by lowlighter** [comment]
By any chance, are these memberships public or private?

If the later, maybe the [following](https://github.com/lowlighter/metrics#-organizations-metrics) could help (i.e add `read: org` scope in token)

As for stars, maybe you have some private repositories starred, which a public token cannot retrieve (a `repo` scope is needed for this)

When you're logged in, GitHub also displays your private content but it may not reflect totally what others are seeing about you. Maybe that would explain why some stats are off, you can check using a private browsing window 🙂

**Comment by LunarWatcher** [comment]
I haven't starred any private repos. That being said, if topics are registered as stars on my profile, but without being counted by the plugin, that explains why the star count is off by 3 (I've starred three different topics)

As for organizations, that's my bad actually. Thought they were public because they were listed on my profile, and I showed up as a member on the individual pages. Would've been nice if GitHub actually said what organizations are private, and which aren't :roll_eyes: Granted the `read:org` scope though, gonna force a regeneration to see if that helped

**Comment by LunarWatcher** [comment]
Yeah, `read:org` dealt with organizations

**Comment by lowlighter** [comment]
Yeah topics aren't counted because the following is used to display this stat:
https://github.com/lowlighter/metrics/blob/cd83e8514636464be7723fdf24efe4889383a666/source/plugins/base/queries/user.graphql#L21-L23

It would be nice to add starred topics too, but last I checked there weren't any GitHub GraphQL API for topics so it's kind of annoying to get this kind of stat. The `topic` actually use puppeteer for this very reason.
Hopefully one day GitHub will implement it.

Glad `read: org` worked, I agree that's not very clear 😅
