### ISSUE TITLE
Language activity converts C++ to C

### ISSUE THREAD

**Issue by LunarWatcher** [lowlighter/metrics#114]
I work with C++, and don't work with C. The language activity section yet drops the ++ and replaces it with nothing, yielding an incorrect language. This is specifically limited to language activity -- most used languages works fine

![image](https://user-images.githubusercontent.com/29489988/107131918-31596200-68db-11eb-9dda-5ec6744f2058.png)

**Comment by lowlighter** [comment]
Thanks for reporting this!
It's probably related to the regex parsing github/linguist output:
https://github.com/lowlighter/metrics/blob/cd83e8514636464be7723fdf24efe4889383a666/source/plugins/habits/index.mjs#L103

It only use `\w` class to detect languages, which does not include special characters like `+` so that's probably why it's dropping them

I'll take a look next week 👍

**Comment by lowlighter** [comment]
Should be fixed in #117
