### ISSUE TITLE
Stargazer stats broke ~6 days ago

### ISSUE THREAD

**Issue by LunarWatcher** [lowlighter/metrics#115]
Good: https://github.com/LunarWatcher/LunarWatcher/blob/42bb1358fa359ba9cbe46020c33d3ff8d26984ff/github-metrics.svg

![image](https://user-images.githubusercontent.com/29489988/107132124-98c3e180-68dc-11eb-94b1-f51bc5d47f96.png)

Bad: https://github.com/LunarWatcher/LunarWatcher/blob/1a7b98fbde6e201088d765a5b9228e6fe98d52f9/github-metrics.svg

![image](https://user-images.githubusercontent.com/29489988/107132130-9feaef80-68dc-11eb-87e3-6c8ad7914f48.png)

It's also currently out of date. Got another star 19 hours ago (at the time of writing) that hasn't clocked in at all. Looks like it decided to blatantly ignore a repo of mine (specifically [this one](https://github.com/lunarwatcher/auto-pairs)) out of the blue.

In the two versions included, there's also a sudden shift in language percentage clocking (Java bumped, C++ dropped) that may be related to whatever changes were made. Currently on the master branch, but this seems to have started with 3.3 (and the same applies to the other two issues I've opened)

**Comment by lowlighter** [comment]
Thanks for reporting this issue, I'll try to investigate what's causing this 👍

**Comment by lowlighter** [comment]
Stargazers display issues should be fixed in #117

Others issues are related to #59 and #61 : 
- forked repositories are ignored by default unless [`repositories_forks`](https://github.com/lowlighter/metrics/blob/master/source/plugins/base/metadata.yml#L30-L34) is enabled (which is the case for mentioned repository)
- sudden shift in language percentage is probably related to the fact that previously only owned repositories were processed but seems that #61 has unattended side effects. I added [`repositories_affiliations`](https://github.com/lowlighter/metrics/blob/master/source/plugins/base/metadata.yml#L37-L45) to allow users to select which `ownerAffiliations` filter to use (none, `OWNER`, `COLLABORATOR` or `ORGANIZATION_MEMBER`)

Let me know if you still encounter issues 🙂

**Comment by LunarWatcher** [comment]
Looks like it works fine again. Thanks!
