### ISSUE TITLE
Disable image caching on web instance

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#128]
Using the web instance image is a bit annoying as it is cached by GitHub leading to outdated stats.

[This](https://stackoverflow.com/questions/23751914/how-can-i-set-response-header-on-express-js-assets) and [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) may help.

**Comment by lowlighter** [comment]
There was actually an error with `cache-control` header in current web-instance where it was cached 1000 hours instead of 1 hour (forgot to convert ms back into sec 😅)

I reduced web instance cache to 900 seconds (15 min) anyway :
```
curl -si https://metrics.lecoq.io/lowlighter | grep cache-control
cache-control: public, max-age=900
```

I can't disable it entirely because of GitHub rate limit (https://github.com/lowlighter/metrics/issues/60#issuecomment-759769896) though the main bottleneck is how svg heights are computed (they're resized trhough a chromium instance)

Hope it'll be better 🙂
___

I enabled a few more plugins on it 👍
