### ISSUE TITLE
Organisation information no longer seems to populate language stats

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#148]
On my profile I list my metrics which includes a language bar. I have one organisation. My cached metrics (last updated at my last edit to [Nixinova/Nixinova](https://github.com/Nixinova/Nixinova) 2 days ago) show 1.5% Liquid, which is from my org. (Liquid is only used in a repo in that org.) However, going to [the web instance](https://metrics.lecoq.io/Nixinova?purge&template=classic&base.metadata=0&pagespeed=1&languages=1&languages.details=percentage&isocalendar=1&isocalendar.duration=full-year) Liquid doesn't appear and instead 0.7% Typescript is shown. It seems that within the past day or so organisation stats no longer populate the metrics. Is this correct?

**Comment by lowlighter** [comment]
Yeah, it has been changed back in v3.4 (which is now the beta version installed on web instance after #128).
It's due to #120 and #115. 

Basically including organizations is fine when you're owner or one of the most active user in it, but in large ones like companies it may include repositories you didn't event worked on from what I understand.

Option `repositories_affiliations` (so `repositories.affiliations` on web instance) was added to let users choose how to filter processed repositories:
https://github.com/lowlighter/metrics/blob/2ea5a457e86ec2c7f1374d41446e35e2238e1392/source/plugins/base/metadata.yml#L37-L47

To get back v3.3 behaviour, add `&repositories.affiliations=` (no filter) to your query.

Options from base content are not referenced (yet) in web instance, but you can still use them 🙂

**Comment by Nixinova** [comment]
Got it, thanks!
