### ISSUE TITLE
Some content (such as achievements) not loading at all because of an unexpected error

### ISSUE THREAD

**Issue by lulunac27a** [lowlighter/metrics#1518]
### Discussed in https://github.com/lowlighter/metrics/discussions/1517

<div type='discussions-op-text'>

<sup>Originally posted by **lulunac27a** August 24, 2023</sup>
Achievements not loading, stuck at **Fetching achievements...** and the top screen shows **Unexpected error** at https://metrics.lecoq.io/insights<img width="1435" alt="Screenshot 2023-08-24 at 8 37 57 PM" src="https://github.com/lowlighter/metrics/assets/100660343/120222f2-4a8d-4db9-b104-6a50bc24c679">
</div>

**Comment by lowlighter** [comment]
Hi 👋 !

Yeah currently because of #1478, achievements cannot be displayed because the fix that has been published is not released yet (will be with v3.34).

In the meantime you can use https://beta-metrics.lecoq.io/insights/lulunac27a instead, which use the main branch instead and includes the latest fixes 🙂 

There's still the message unexpected error though, I haven't looked yet why this occurs, but achivements should be visible on the beta website

**Comment by lulunac27a** [comment]
I tried `- uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36`, `- uses: lowlighter/metrics@master` and `- uses: lowlighter/metrics@latest` in .github/workflows/main.yml, but all I tried, the achievements are not working due to an unexpected error:
```
Rendering                                                       │  
1 error(s) occurred
  [
    {
      name: 'achievements',
      result: {
        error: {
          message: 'Unexpected error',
          instance: 'Failed to initiate total for achievement plugin'
        }
      }
    }
  ]
Status                                                          │ complete
MIME type                                                       │ image/svg+xml
```

**Comment by lulunac27a** [comment]
The achievement plugin is now working.
