### ISSUE TITLE
Run failing for runing more then 360 minutes

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#169]
See [this workflow](https://github.com/Milo123459/Milo123459/actions/runs/616102415) as an example.

**Comment by Milo123459** [comment]
When that was running it was using master fyi.

**Comment by Milo123459** [comment]
This appears to be a jimp issue

**Comment by aleen42** [comment]
Same question in [my action](https://github.com/aleen42/aleen42/runs/2019626401?check_suite_focus=true)

**Comment by lowlighter** [comment]
Yeah `@master` branch seems broken for now, seems that the puppeteer resizer is ko.
I'm checking it currently

**Comment by lowlighter** [comment]
Still on it, but seems it's an issue with puppeteer (workflows runs stops just before opening the page used to resize the svg height) where a promise never resolves.

Not sure what broke it since it still works on localhost so it's probably a bad behavior from github actions + docker + puppeteer + headless chromium combo.

Downgrading puppeteer to 7.1.0 (same as latest) or upgrading to 8.0.0 makes no differences

I'll try to debug when I have some free time, but it may take a few days so you can switch to `@latest` in the meantime if you want to update your metrics (`@latest` still works since image is pre-built)

**Comment by lowlighter** [comment]
Seems that e52cefe actually solved it
