### ISSUE TITLE
Scaling issue (reactions plugin)

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#183]
![img](https://salvage.is-inside.me/BD20hIki.png)

When using config_twemoji and that, it'll break as it is too big. Also, how can we make it display both percentage and count?

**Comment by lowlighter** [comment]
Yeah they're a bit big 😅
I need to check it out, I actually copied these from pagespeed plugin, but the center text is a svg `<text>` node which does not support embedding additional svg (which are required for twemojis) but it works fine on regular emojis since it's text-based.

It could be quite tricky to fix

___

As for second question, it's not possible yet to display both percentage and count for now, but I'll work on it 👍🏼  
Should be available later today

**Comment by Milo123459** [comment]
1) Sounds good, let me know if I can help
2) Same with number 1
3) No problem, I love this project and I'd love to make it better!

**Comment by lowlighter** [comment]
2 has been pushed to master 👍🏼 

___

For 1, if you want to check it out, maybe by tweaking the css or moving it to the `templates/styles.css` you'll be able to solve it: 
https://github.com/lowlighter/metrics/blob/d3103287f0b55e47d78c229ee23551e3036c444a/source/templates/classic/partials/reactions.ejs#L17-L22

I'm pretty sure it's possible to patch css only because on a windows local server with firefox it does works:
![](https://user-images.githubusercontent.com/22963968/110784183-ab2d9400-8269-11eb-8d56-21948d08aa41.png)

Tricky part is that twemoji are post-processed so you cannot actually edit them directly.
But they do have a `twemoji` css class, so maybe using `.gauge.info .twemoji` to apply css resizing may work too

**Comment by Milo123459** [comment]
Yea. Will look into it.

**Comment by Milo123459** [comment]
Found nothing 😔
Tried changing scales, css, nothing.

**Comment by lowlighter** [comment]
Seems a browser issue.
On firefox and safari (mobile) it works, but not on chromium based browser like chrome and edge 😕

**Comment by Milo123459** [comment]
Can we use a normalisation library to fix this issue?

**Comment by lowlighter** [comment]
I'm not sure what you mean by a normalisation library

**Comment by Milo123459** [comment]
[This](https://npmjs.com/package/modern-normalize)

**Comment by lowlighter** [comment]
Maybe, that's something that could be tested yes 🙂

**Comment by Milo123459** [comment]
Cool! Will try

**Comment by lowlighter** [comment]
Once [build](https://github.com/lowlighter/metrics/actions/runs/651256175) is done (and succeeds), it should be fixed after a retry

**Comment by Milo123459** [comment]
Alrighty, will close and re-open if error persists.
