### ISSUE TITLE
Metrics website error while generating metrics.

### ISSUE THREAD

**Issue by kimlimjustin** [lowlighter/metrics#195]
![5396f8dc-eeae-4b9e-ad1a-e5565bbff16a](https://user-images.githubusercontent.com/61906684/111911593-d51c5d00-8a98-11eb-9d4d-efa29152eca7.png)

I refreshed it but also display the same error. 
Hope will be fixed soon :)

**Comment by lowlighter** [comment]
Sorry for the inconvenience 🙇
It should be better now.

If you find a good configuration, I suggest copying the action code to setup a GitHub Action workflows on your repository, so you'll always have your metrics, even if the server is down. Plus you'll have access to all available plugins 🙂

**Comment by kimlimjustin** [comment]
Thanks :)

**Comment by kimlimjustin** [comment]
Idk why but the metrics also show the same error now (ps: I was just wanna to test another feature in the website, I got the metrics on my profile too)

**Comment by lowlighter** [comment]
I'll investigate on what causes this when I have some free time this week 👍🏼  

It seems that you're unlucky though because using other accounts do work, but yours don't (I can indeed reproduce the issue using your username) 😕 

But don't worry, I'll eventually figure why and patch it, thanks for your patience 🙂  !

**Comment by lowlighter** [comment]
I think it's fixed, let me know if you still encounter problems 🙂

**Comment by kimlimjustin** [comment]
Yes, it works, thanks!
