### ISSUE TITLE
Terminal template svg height does not fit content

### ISSUE THREAD

**Issue by kimlimjustin** [lowlighter/metrics#201]
I found out that there is a `height="344"` attribute at the SVG tag that makes it display only 344 pixels of height when I was trying the terminal template on the website. 

![Untitled](https://user-images.githubusercontent.com/61906684/112477159-431c9900-8da5-11eb-97e3-7f80006cbca9.png)

Removing that element will make it looks normal :)
![Untitled](https://user-images.githubusercontent.com/61906684/112477298-6e06ed00-8da5-11eb-8b3c-d5b3afcc5686.png)

**Comment by lowlighter** [comment]
I'll check, it probably comes from the core resizer which doesn't disable correctly the css animations before cropping the image, hence why only a portion of final render is visible.

Removing `height` attribute may work on website but that's probably because images are rendered directly like html (so height is computed automatically using bounding boxes, etc), but I'm pretty sure it won't on GitHub since it's displayed through an `<img>` which does not behave the same

**Comment by kimlimjustin** [comment]
Okay!

**Comment by lowlighter** [comment]
Code has been fixed (local image were resized without animation despite the server already computed height)
It'll be fixed on website this afternoon 🙂

**Comment by kimlimjustin** [comment]
Okay, thanks!
