### ISSUE TITLE
Recent activity plugin marks closed pull requests as "Merged"

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#213]
When a PR is closed, it is logged in the "recent activity" plugin as "Merged #N" instead of "Closed #N".

Problem probably lies with a missing check on this line:

https://github.com/lowlighter/metrics/blob/a98530dd6bf87f826b2efe7d8c2b8921ce3b5f78/source/templates/markdown/partials/activity.ejs#L24-L26

**Comment by lowlighter** [comment]
Yeah I think both classic/markdown templates have this issue for pull requests.

That's because the [PullRequestEvent](https://docs.github.com/en/developers/webhooks-and-events/github-event-types#pullrequestevent) doesn't directly tell if a PR has been merged when it's closed.

It seems that it's located deeper in the payload as noted [here](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-object-33), so if the `merged` key is `true` and the `action` is `closed` we should override it to `merged` in the following snippet:

https://github.com/lowlighter/metrics/blob/c8bfbcafbae7cefe24ff8bcba7bca25b6db18057/source/plugins/activity/index.mjs#L87-L93 

It should not be too hard to patch I think
