### ISSUE TITLE
Organisation count is 0

### ISSUE THREAD

**Issue by TheShubhendra** [lowlighter/metrics#221]
I am member (owner) of 3 organisation but this is not reflecting on the banner https://metrics.lecoq.io/TheShubhendra
![Banner](https://metrics.lecoq.io/TheShubhendra)

**Comment by lowlighter** [comment]
Your current memberships are not public, you're only seeing them because you're logged in :)
You can change their visibility within your organization settings:
<img src="https://user-images.githubusercontent.com/22963968/114211601-206fb000-9961-11eb-9d3b-356617f0eb19.png" width="700">

If you use the GitHub Action instead of the website, you must grant the `read:org` scope

See [Organizations memberships for user accounts](https://github.com/lowlighter/metrics#-organizations-metrics) for more informations 👍🏼
