### ISSUE TITLE
Image is randomly cut off the side

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#223]
![img](https://salvage.is-inside.me/jUYp5hTp.png) as you can see, it's kinda cutting off the edge. https://github.com/Milo123459/Milo123459/blob/master/github-metrics.svg < there is the svg.

**Comment by lowlighter** [comment]
![](https://user-images.githubusercontent.com/22963968/114266207-58283780-99f5-11eb-9e20-3234283be315.png)

I think there's an unclosed div somewhere in tweets attachments which make them expand indefinitely (thus why you're seeing a gray bar all the way till the bottom), and because of the "indent" of tweet, all subsequent plugins are cropped right 😕

Actually it may be related to #172 with a certain extent which was having weird tweets attachments too

As a "workaround" for know, I think disabling the tweets attachments option will solve your issue, until we can find a fix for this 🙂

**Comment by Milo123459** [comment]
👍 Let me know how I can help, haven't contributed to this project in a while so I may as well start again! :-)

**Comment by lowlighter** [comment]
I'm on mobile right now so I can't link code parts easily 😕

But good places to start are:

Template which may have an unclosed html tag:
https://github.com/lowlighter/metrics/blob/b7c4f6e5bbc3506a2f0aa59879eb024b103d7850/source/templates/classic/partials/tweets.ejs

Plugin which do some html transforms: 
https://github.com/lowlighter/metrics/blob/b7c4f6e5bbc3506a2f0aa59879eb024b103d7850/source/plugins/tweets/index.mjs

The tweets plugin is evalued "rawly" by the template (html is interpreted, though the tweet text is normally escaped).

So I think one would need to check first if plugin output send correct html, and then try to play with the template to find which part is causing issues

I'm pretty sure it's a html tag problem, but it's just a feeling so maybe the issue actually comes from somewhere else

Let me know if you're taking a look at it and find something interesting 🙂

**Comment by Milo123459** [comment]
Will do!

**Comment by lowlighter** [comment]
I plan on releasing v3.7 in 2-3 days (as it's already quite dense in features)
If you already found something and think you'll be able to make it through next release (same for #225 if you started working on it) I can wait a few more days if you want 🙂 

Else we'll keep this issue open and probably patch it in v3.8 👍🏼
