### ISSUE TITLE
Weird tweet attachment behaviour

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#224]
It's getting the attachment from a completely unrelated tweet: ![image](https://user-images.githubusercontent.com/50248166/114248745-67c16500-9990-11eb-8670-9b9560a88c98.jpeg)

**Comment by lowlighter** [comment]
![image](https://user-images.githubusercontent.com/22963968/114266623-873fa880-99f7-11eb-9a2f-429f1bf91211.png)

Seems it disappeared?

But if you still have it, it's probably related to #223. There's a gray bar before the unrelated tweets which makes me think it's getting mixed because of an unclosed tag

Thanks for the reports 🙂 !

**Comment by Milo123459** [comment]
I think it might be how the open graph protocol is messing with it, ie, the embed stuff

**Comment by lowlighter** [comment]
Yes, it could be possible too

Code for it is located around the same parts as linked in #223 if you want to investigate on it too

**Comment by lowlighter** [comment]
Tested on multiple accounts today and this issue seems to be gone
Feel free to re-open if it occurs again 🙂

**Comment by lowlighter** [comment]
Seems it was actually caused by empty div getting converted in self-closing tags which was creating unclosed tags
