### ISSUE TITLE
🐞: Orgnaizaion count seems incorrect

### ISSUE THREAD

**Issue by joe733** [lowlighter/metrics#29]
**Bug description**
I guess the headline speaks :)

**Expected behavior**
The organizations are correctly counted.

**To Reproduce**
Just make a successful build.

**Additional context and screenshots**
![Screenshot from 2020-12-28 09-35-48](https://user-images.githubusercontent.com/38415384/103189984-11ef1280-48f5-11eb-91fd-98fa741170a2.png)

Shouldn't organization count be 2 here 🤔?

**Comment by lowlighter** [comment]
Hello again 🙂, 

From what I've seen, it's probably because you're only part of private organizations.

When others users are looking at your profile, you're not listed in any organization, which seems to match the GraphQL api response : 
<img src="https://user-images.githubusercontent.com/22963968/103212333-c7789080-490a-11eb-8059-db41e7e26761.png" width="500">
<img src="https://user-images.githubusercontent.com/22963968/103212230-913b1100-490a-11eb-81e7-d7724d7e2396.png" width="500">

What you could try though, is to update the scopes of the personal token you're using with these permissions : 
![image](https://user-images.githubusercontent.com/22963968/103213806-14f6fc80-490f-11eb-9fa5-087195843efc.png)

I'm guessing that `read:org` should work from its description, but I'm not 100% sure.
If it works, I'll update documentation, as it's actually a nice catch.

If not, I'll investigate more 👍

**Comment by joe733** [comment]
Hi 👋🏻,

Thanks, I didn't know about this, nice. So I tested it with one private and another public membership. Updated the token with `read:org` privileged and yes it works like charm!

I've made a PR #31 which adds some clarification to the documentation, I hope 🙂
