### ISSUE TITLE
Inconsistent and incorrect fork count

### ISSUE THREAD

**Issue by LunarWatcher** [lowlighter/metrics#301]
The header says 17 forks, the "body" or whatever says 10 forks.

![image](https://user-images.githubusercontent.com/29489988/118332750-e0c15880-b50a-11eb-8d80-54290c5544e3.png)

On top of that, both of these are wrong. A quick search indicates that I have 16 forks (not 17 and not 10). I do have 10 archived repos, however

**Comment by lowlighter** [comment]
For some reason [LunarWatcher/focus.vim](https://github.com/LunarWatcher/focus.vim) appears to be a fork of [beauwilliams/focus.nvim](https://github.com/beauwilliams/focus.nvim) but is not displayed when using GitHub search filter [LunarWatcher?tab=repositories&q=&type=fork](https://github.com/LunarWatcher?tab=repositories&q=&type=fork&language=&sort=) which indeed which show only 16 forks, though when counted manually using repositories tab 17 seems correct. Not sure if it's because it's archived like you suggested and GitHub hides them by default?

As for the second stat in the "body", it's more a matter of wording and I concede it's not very clear (not sure how to formulate it). 
These actually represent the number of times your repositories have been forked (that's why it's the same place as watchers and stargarzers).
For forked repositoies, it may not take into account the number of forks from the original repo like GitHub does though, and use the "real" number of forks from forks. 

Let me know if these stats still seems innacurate after these explanations 🙂

**Comment by LunarWatcher** [comment]
Oh, right - that's actually my bad. GH filters are kinda dumb. Filtering by anything only includes that specific type (meaning fork filters only include non-archived forks, sources only include non-archived sources etc.). I forgot about that when writing this :') In that case, the fork count is correct (17, not 16).

**Comment by lowlighter** [comment]
I didn't even know about this x)

Maybe "X repositories forks" or "X times forked" would be more explicit for second stat?

**Comment by LunarWatcher** [comment]
The second option makes more sense, and would definitely be better

**Comment by lowlighter** [comment]
I changed it to "forkers" instead, to be more inline with "stargazers" and "watchers" 
Thanks a lot for your feedback
