### ISSUE TITLE
Excessive whitespace present at the end of image

### ISSUE THREAD

**Issue by austinhuang0131** [lowlighter/metrics#321]
Basically a relapse of #33. It seems to be reproducible on every existing implementation. Also the amount whitespace seems to be correlational to amount of modules present, and `config_padding` does not seem to work either.

**Comment by Nixinova** [comment]
I do get this sometimes but it doesn't seem present in the actual svg usually

**Comment by lowlighter** [comment]
`config_padding` was indeed broken since probably v2.0 or maybe even more.

The `%` sign was actually not supported and has been patched like 2 days ago on `@master`, though I did not find any satisfying default values yet.

Previously, only default value was considered, which includes relative padding and explain why the more modules are enabled, the more padding gets added.

If you're on `@master` and find suitable values for `config_padding`, don't hesistate to report it 🙂

**Comment by austinhuang0131** [comment]
`16, 36` seems good if including `metadata`, but it seems like `16, 0` will just cut off the metadata

**Comment by Nixinova** [comment]
Heres how it appears by default

![Screenshot_20210526-110023](https://user-images.githubusercontent.com/42429413/119579024-afe9f900-be11-11eb-9c5c-27a51ce86906.png)

**Comment by lowlighter** [comment]
Current defaults seems ok now I guess.

There are still excess whitespace on really large images (like when enabling all plugins at once) but I don't think it's possible to find a one-for-all setting unfortunately 😕

**Comment by Nixinova** [comment]
Now I've got the opposite problem

![image](https://user-images.githubusercontent.com/42429413/120269132-55fa9f00-c2fb-11eb-8b59-4b98798d1520.png)

**Comment by lowlighter** [comment]
I'll increase the padding a bit more, seems that it's almost good

**Comment by Nixinova** [comment]
When pagespeed insights returns error 429 the passing should be lessened

**Comment by Nixinova** [comment]
This still occurs

![Screenshot_20210626-142113](https://user-images.githubusercontent.com/42429413/123499293-ce9a1480-d689-11eb-9a02-1f044fb160ec.png)

**Comment by Nixinova** [comment]
Still happens on mobile. @lowlighter this should be tagged `needs-fix`.

**Comment by lowlighter** [comment]
Closing in favor of  #814
