### ISSUE TITLE
Recent languages stats includes info from fast-forwarded merges

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#338]
Four hours ago I generated [these metrics](https://github.com/Nixinova/Nixinova/blob/d1a96a778803acf1d22a5d9fa275a8ca9df8d761/github-metrics.svg).

![Screenshot_20210528-173404](https://user-images.githubusercontent.com/42429413/119935036-ef177600-bfda-11eb-9b6c-46fc36f3524c.png)

Just now i generated [these](https://github.com/Nixinova/Nixinova/blob/98439f807533c0130b8b01fc7a08e22c94f11611/github-metrics.svg)

![Screenshot_20210528-173430](https://user-images.githubusercontent.com/42429413/119935078-ff2f5580-bfda-11eb-8b5d-a87673ec5958.png)

I assume the plugin is counting the uncollapsed merge commit I did of this repo (via GitHub's new "fetch upstream" feature) – this doesn't create a new merge commit so it may be hard to filter.

![Screenshot_20210528-173611](https://user-images.githubusercontent.com/42429413/119935246-4b7a9580-bfdb-11eb-9971-dab4a92ece00.png)

Version https://github.com/lowlighter/metrics/commit/fb745b42bb3096dfeabae789a8b1c2f0f05ad48a

**Comment by Nixinova** [comment]
Yep that's definitely the issue, I fetched multiple forks and made [this](https://raw.githubusercontent.com/Nixinova/Nixinova/ef15096db99183a512da63c7e38b1241bf8cb74d/github-metrics.svg)

**Comment by Nixinova** [comment]
Also what happened to Ruby's colour?
![Screenshot_20210528-174447](https://user-images.githubusercontent.com/42429413/119935926-71ed0080-bfdc-11eb-97c2-5e503f54a99e.png)

**Comment by Nixinova** [comment]
Even using indepth it still shows them [link](1https://github.com/Nixinova/Nixinova/blob/3cb684dcaac36bcf13a649ec8d882d252c9b15f6/github-metrics.svg)

**Comment by Nixinova** [comment]
Insights also seems a bit off, my TypeScript just halved

**Comment by lowlighter** [comment]
So after debugging a bit, *PushEvents* included commits from other authors like you hinted, `44e1a84` should improve first 2 points

Since commits can be authored through differents names/emails, you may need to fill out the new option `commits_authoring` to tell how you usually sign your commit (it defaults to your github username)

You can use your email address for instance: 
```yaml
commits_authoring: 22963968+lowlighter@users.noreply.github.com
```

**Comment by Nixinova** [comment]
> Insights uses the default non-indepth behaviour so it may include code you didn't write (it only looks at bytes per language on repositories) so it's kind of skewed by default 😕

All TS code has been written by me, though. I'll see if it works with the new change.

**Comment by Nixinova** [comment]
This much more accurate, thanks

![image](https://user-images.githubusercontent.com/42429413/120040944-920fd480-c05b-11eb-8013-f1cb73ea4230.png)

**Comment by lowlighter** [comment]
> > Insights uses the default non-indepth behaviour so it may include code you didn't write (it only looks at bytes per language on repositories) so it's kind of skewed by default 😕
>
> All TS code has been written by me, though. I'll see if it works with the new change.

It depends, since insights is not able to distinguish between code you actually wrote or are closely related because you contributed to repository, maybe your html/js stats are over represented in terms of bytes on it. It'll indirectly impact your others languages stats since it's displayed as percentages:

![](https://user-images.githubusercontent.com/22963968/120040448-db820480-c006-11eb-86e5-fb9bfbef1bba.png)

Maybe when using indepth your typescript bytes stats don't change that much but the html/js is lowered a bit, thus increasing your typescript percentage 🤔 ?

> This much more accurate, thanks

Nice, glad to hear it 🙂

**Comment by Nixinova** [comment]
> Maybe when using indepth your typescript bytes stats don't change that much but the html/js is lowered a bit, thus increasing your typescript percentage

I was using mcfunction as a baseline as it stayed at 8% while TS dropped by half so something had to be wrong there.

**Comment by Nixinova** [comment]
Ah, I know why, my email for old commits in there is `Nixinova@users.noreply.github.com` while my new one is `42429413+Nixinova@users.noreply.github.com`.

**Comment by lowlighter** [comment]
> I was using mcfunction as a baseline as it stayed at 8% while TS dropped by half so something had to be wrong there.

I checked the code, insights actually use default `repositories_affiliations: owner`, and you've set `repositories_affiliations: ''` so maybe the offset come from here?

> Does indepth load organisation repos? 

Yes if it's working correctly it should load all repositories you ever contributed to (at least the one that are reported by GitHub API, I'm not sure whether there is a time window on it)

> Can I have multiple options in commits_authoring? 

It should support it, but I didn't tested it intensively 😅

**Comment by Nixinova** [comment]
`commits_authoring: Nixinova@users.noreply.github.com, 42429413+Nixinova@users.noreply.github.com` didn't work at all

**Comment by lowlighter** [comment]
I tested quickly in local, it seems to be a case-sensitivity issue
All array inputs are automatically lower-cased by default so nothing was matching your emails, it should be patched on next docker image rebuild

**Comment by Nixinova** [comment]
It doesn't seem different even with that change
![Screenshot_20210529-122250](https://user-images.githubusercontent.com/42429413/120052285-a31b0e80-c078-11eb-96a4-ea8c804be023.png)

**Comment by lowlighter** [comment]
So I've made a small cli alias to make it possible to directly call the indepth analyzer without spawning metrics entirely:
```js
> npm run indepth -- "Nixinova@users.noreply.github.com, 42429413+Nixinova@users.noreply.github.com" ~/novasheets
commits authoring | nixinova@users.noreply.github.com,42429413+nixinova@users.noreply.github.com
repository path   | ~/novasheets

{
  total: 73543,
  lines: { JavaScript: 364, TypeScript: 1133, Less: 40, HTML: 181 },
  stats: { JavaScript: 13690, TypeScript: 52718, Less: 1400, HTML: 5735 }
}
```

I think it's probably a oom issue from the runner. Currently 10 commits are loaded at the time, but sometimes `git log` exit with a `null` code so these are skipped. I uploaded the code to load each commit separately for now which yields the above results which seems to match more or less the api call:

```js
{ JavaScript: 11672, TypeScript: 44309, Less: 1479, HTML: 464 }
```

Stats are lower because GitHub only report current commit's repo files size but indepth will catch code you may have refactored since

Best solution would probably to use a custom process runner for github-linguist which processes the stdout stream instead of loading it all at once but this can always be improved in futures releases

**Comment by Nixinova** [comment]
This is suddenly more accurate I think

![image](https://user-images.githubusercontent.com/42429413/120083468-f3e44300-c11c-11eb-8f29-7c135e2c6825.png)

**Comment by Nixinova** [comment]
Now all of a sudden my recent language stats (generated June 6 @ 20 UTC) have been multiplied by like 10. I didn't touch Java at all that day but it went up from 260 to 2.3K. [link](https://github.com/Nixinova/Nixinova/commit/78ee0add88b029a1311f2a2d020999bc7a4b3c61)

**Comment by lowlighter** [comment]
Yes, instead of committing repos separately it was counting all edited repos multiple times
Sorry for the inconvenience 😅
