### ISSUE TITLE
Indepth language analysis doesn't load all language colors

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#339]
Moving from #338
> Also what happened to Ruby's colour?
![Screenshot_20210528-174447](https://user-images.githubusercontent.com/42429413/119935926-71ed0080-bfdc-11eb-97c2-5e503f54a99e.png)
&mdash;https://github.com/lowlighter/metrics/issues/338#issuecomment-850151030 by me

> When using indepth feature, colors aren't fetched from GitHub (I didn't check whether it's possible to get them through api).
If the color for the languages wasn't loaded beforehand through the GraphQL API (i.e. like the non-indepth behaviour), it defaults to the gray color.
&mdash;https://github.com/lowlighter/metrics/issues/338#issuecomment-850357833 by @lowlighter

**Comment by Nixinova** [comment]
What's the difference between `bug` & `needs-fix`?

**Comment by lowlighter** [comment]
It's the label to prevent the ci to mark it as stale, probably wasn't inspired when searching for a label name 😅

**Comment by Nixinova** [comment]
I tried earlier to replace the color fetching with data from Nixinova/Linguist but couldn't quite find where to find the code that needed to be replaced.

**Comment by lowlighter** [comment]
The `analyzers.mjs` exploit the fact that JS pass objects as reference so they can be edited by sub-functions.
https://github.com/lowlighter/metrics/blob/21c97bd654bfb098dd025764e054b55f0154f08c/source/plugins/languages/analyzers.mjs#L32

The `analyze` function writes directly in the `results` object, which currently don't have any `colors` property: 
https://github.com/lowlighter/metrics/blob/21c97bd654bfb098dd025764e054b55f0154f08c/source/plugins/languages/analyzers.mjs#L7

Since the returns of analyzer is merged with `Object.assign` into `languages` plugin result:

https://github.com/lowlighter/metrics/blob/21c97bd654bfb098dd025764e054b55f0154f08c/source/plugins/languages/index.mjs#L66

Finding a way to set `result.colors` to `{[language.toLowerCase()]:color}` in `analyze` function based on `languagesResult` return should do the trick.

The only drawback is that we need to find a way to support `plugin_languages_colors` (user defined colors) but not sure what's the cleanest way to do it.

Maybe loop onto the `colors` variable in `index.mjs` to override them?
https://github.com/lowlighter/metrics/blob/21c97bd654bfb098dd025764e054b55f0154f08c/source/plugins/languages/index.mjs#L30

**Comment by Nixinova** [comment]
I tried to implement it with https://github.com/lowlighter/metrics/compare/21c97bd654bfb098dd025764e054b55f0154f08c...42e4e565d08905372be34d82cc1acf0f19be049a however I can't get it to work.
