### ISSUE TITLE
Getting An Error when ran GitHub actions

### ISSUE THREAD

**Issue by JayantGoel001** [lowlighter/metrics#34]
**Bug description**
Hey @lowlighter
I am Getting an error please help me with it.

**Expected behavior**

**To Reproduce**

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/54479676/103423542-2a994a00-4bcd-11eb-8fa7-386c780e458e.png)

**Comment by lowlighter** [comment]
Hi!

I was experimenting some stuff with GitHub actions today directly onto `@master` so it was broken the whole day 😅
It should be working now if you pull `@master` now, (at least my personal workflows seems to be ok).

For reference, I'm trying to make future released versions using a published docker image on GitHub registry directly instead of rebuilding it each time, to improve workflow performances (from ~5min to < 30sec).
It's not 100% ready though, but it'll be nice to have 👍

**Comment by JayantGoel001** [comment]
Hi @lowlighter 
Ya It Worked Now.
Thanks

**Comment by lowlighter** [comment]
It's better now, but it still needs some padding, will add it later
