### ISSUE TITLE
`plugin_languages_recent_days` doesn't do anything

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#345]
No matter what value I pass to `plugin_languages_recent_days` I get the same output.

![Screenshot_20210531-112731](https://user-images.githubusercontent.com/42429413/120123719-99bead00-c204-11eb-862e-33a01449de55.png)
![Screenshot_20210531-112717](https://user-images.githubusercontent.com/42429413/120123720-9b887080-c204-11eb-8620-46701d79a861.png)
![Screenshot_20210531-113623](https://user-images.githubusercontent.com/42429413/120123716-962b2600-c204-11eb-9e7b-fb797f3132f1.png)

   https://github.com/lowlighter/metrics/blob/2ae690fac73120264a7221f821e0e708c11f3fc4/source/plugins/languages/analyzers.mjs#L63

**Comment by lowlighter** [comment]
It's possible that your events don't cover whole 14 days, and unfortunately even if you try loading more events using `plugin_languages_recent_load` option, there's no guarantee that GitHub will be able to give you more.

From the estimation text, you can see that actually 2 more commits were found between 7-14 days (percentages are slightly different) and you probably reached the oldest event that can be loaded

If you test with a really low setting, you'll see more changes (these are your stats for last day):
![image](https://user-images.githubusercontent.com/22963968/120180986-bd85f100-c20c-11eb-9839-51488db59fba.png)

**Comment by Nixinova** [comment]
Hm, okay, I was sure I hadn't done 4k JS in the past week. Is there a way to reflect that it's reached the maximum in the total-days count and have it change to the oldest day reached? So if it only reached May 20 it would say "past 11 days" instead of "past 30 days"

**Comment by lowlighter** [comment]
> Hm, okay, I was sure I hadn't done 4k JS in the past week

Maybe there are still adjustements to do on this feature since it's relatively new, if you find anything which makes stats incorrect like in #338 don't hesitate to report it 🙂 

It's possible that there are some "noises" that get counted in like added empty lines, moved code blocks (the same lines may count multuple times if you change it place) or single characters lines like brackets `}`

> Is there a way to reflect that it's reached the maximum in the total-days count and have it change to the oldest day reached? So if it only reached May 20 it would say "past 11 days" instead of "past 30 days"

Yes, it shouldn't be too hard to do, essentially we just need to load the `created_at` date from the last commit event fetched:
https://github.com/lowlighter/metrics/blob/37f686a2ac804b88958992689b66212556e8afd3/source/plugins/languages/analyzers.mjs#L70-L71

And change the value used in the template:
https://github.com/lowlighter/metrics/blob/37f686a2ac804b88958992689b66212556e8afd3/source/templates/classic/partials/languages.ejs#L23

**Comment by Nixinova** [comment]
> Hm, okay, I was sure I hadn't done 4k JS in the past week

Found what this was, it was JS files I had marked as generated using gitattributes.

**Comment by lowlighter** [comment]
Yes the recent analyzer doesn't load the `.gitattributes` of the related repo currently

I'll check to create "temporary partial repositories" from event patches instead of just storing them in the same folder and fetch the `.gitattributes` at least once so linguist is more accurate in its result
