### ISSUE TITLE
The website of the project is not loading in Safari 14.0.3

### ISSUE THREAD

**Issue by omerayyildiz** [lowlighter/metrics#39]
**Bug description**
The website of the project is not loading in Safari 14.0.3. This problem goes away when I turn on responsive mode in Safari.

**Expected behavior**
Opening the project in Safari (14.0.3 - Big Sur Version 11.2 Beta (20D5029f)).

**To Reproduce**
I Don't know 🤷🏻‍♂️ 

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/34156233/103817440-c0beeb80-5077-11eb-9360-a8a60d0332d2.png)

![image](https://user-images.githubusercontent.com/34156233/103817471-cd434400-5077-11eb-9ec6-fa7e315608bc.png)

![image](https://user-images.githubusercontent.com/34156233/103817542-f368e400-5077-11eb-84b6-4f0bead9a46c.png)

**Comment by lowlighter** [comment]
Hello, thanks for reporting this bug !

I actually had the same issue on iOS Safari and patched it with some hacky patch involving `@media` queries, but I guess it doesn't work for desktops then. 

There is probably some css behaving differently in Safari from other browsers, but I'm not really sure myself since I don't have a Mac. 

I would say it has something to do with `height: 100%` of `nav`, which is taking the full page height instead of its parent container, or maybe one of the `flex-grow`/`flex-schrink` is misinterpreted. Since there is an `overflow: hidden` in `main`, I think that's why the remaining part is not displayed.

The html/css needs a bit of cleaning anyway so hopefully it'll be fixed when it gets cleaner. 

Seems you already found workaround for now, switching browser or resizing Safari windows to trigger the mobile view should display an usable version.

I'll investigate when I got some time.

Have a nice day !

**Comment by omerayyildiz** [comment]
Thank you for taking care. It's ok for me to log in from Chrome or any other browser.

I found this link to test it in Safari. It might work for you.
[BrowserStack](https://www.browserstack.com)

**Comment by lowlighter** [comment]
Should be fixed with #47
By the way, BrowserStack is really cool!

**Comment by omerayyildiz** [comment]
Yesss, it works 🥳

![image](https://user-images.githubusercontent.com/34156233/104652926-de6d0000-56ca-11eb-89e6-9d663dfa4bd7.png)
