### ISSUE TITLE
Skyline Year is Weird

### ISSUE THREAD

**Issue by iop3** [lowlighter/metrics#395]
I set the `plugin_skyline_year` to 0 so it will show the current year (2021) but it shows 2008.

**Comment by spenserblack** [comment]
[It looks like it actually checks if it's NaN](https://github.com/lowlighter/metrics/blob/2afece0f847505a0932d58b7f77996445ac5c941/source/plugins/skyline/index.mjs#L11).

Maybe this will work :thinking:
```yaml
plugin_skyline_year: .NAN # Some parsers convert to null, others convert to NaN
```

**Comment by lowlighter** [comment]
Seems the `README.md` of the skyline plugin is not right, like @spenserblack said, any input that would be converted to `NaN` should work

https://github.com/lowlighter/metrics/blob/2afece0f847505a0932d58b7f77996445ac5c941/source/plugins/skyline/metadata.yml#L15-L20

We should either update the doc or maybe change `if (Number.isNaN(year))` to `if (Number.isNaN(year) || year === 0)` since a lot of plugin actually use `0` as a special value so it would makes sense

**Comment by spenserblack** [comment]
`NaN` is falsy (`!!NaN === false`), so a simple `if (!year)` might work (this would also support null `year` values).

**Comment by spenserblack** [comment]
Unless if `Number.isNaN` was used to check the *type* of the value?
[`Number.isNaN` will return *`false`* if the type is *not `'number'`*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN). That could possibly be a related bug.

i.e. `Number.isNaN('current-year') === false`.

**Comment by spenserblack** [comment]
Is the metadata's `type` value used for converting the value passed in the workflow? I had originally assumed it was just documentation, but it must be doing that since `Number.isNaN('current-year') === false` but `Number.isNaN(Number('current-year')) === true` :thinking:

**Comment by iop3** [comment]
Thanks a lot! It worked! 😁

**Comment by lowlighter** [comment]
> NaN is falsy (!!NaN === false), so a simple if (!year) might work.

Yes, plus it's easier to understand it 👍 


> Is the metadata's type value used for converting the value passed in the workflow?

Yes indeed 🙂 

The reason behind is that GitHub passes all inputs as environment variables to actions, so these are implicitely casted to strings (that's also why arrays and dictionnaries cannot be used currently in any `action.yml`, though I've seen that GitHub recently added new features to parse multilines strings into array in `actions/core`). It's also the same for query parameters when using web instances, which are implicitely strings since there are no typing.

So although kind of hacky, the `metadata.mjs` parses the `metadata.yml` of each plugin to automatically validate and sanitize user inputs, with additional casting and defaulting to avoid inputs checks at the beginning of each plugin. It also kind of act as documentation as a bonus

___

> Thanks a lot! It worked! 😁

Glad you were able to make it work!
