### ISSUE TITLE
Unable to use the workflow

### ISSUE THREAD

**Issue by vinayakkulkarni** [lowlighter/metrics#398]
Workflow Bug – https://github.com/vinayakkulkarni/vinayakkulkarni/runs/2882505129?check_suite_focus=true#step:2:386

Followed the docs/setup & added the METRICS_TOKEN as well in the repo secrets.

**Comment by lowlighter** [comment]
Seems to be some timeout issues on GitHub's side because you're a very active user 🙂 
It happens for users with lot of repositories, commits and contributions, but unfortunately I don't have any ideas of how to solve these issues currently 😕 

`base` and `languages` plugins are both dependant of this [graphql query](https://github.com/lowlighter/metrics/blob/master/source/plugins/base/queries/user.graphql) which often timeout for your account so these won't work.

Most plugins are standalone now though, so they should work fine if you use them without a base-dependant plugin (like `isocalendar` and `topics` in your case). For `notable` plugin, you'll need to lower `repositories_batch` option to something like 10 so it's able to load everything at the cost of making more queries
