### ISSUE TITLE
Non-'standard' license types not handled correctly [Stars Plugin]

### ISSUE THREAD

**Issue by aw1cks** [lowlighter/metrics#399]
Hey!

Thanks for writing this cool project :slightly_smiling_face:

It looks like some license types are not being handled correctly.
If I had to guess, something (not) being returned [here](https://github.com/lowlighter/metrics/blob/master/source/plugins/stars/queries/stars.graphql#L16) is not accounted for.

Here's [an example](https://github.com/aw1cks/aw1cks/blob/c4c889300ccb64c7676c2100d9f7f7132d7ab349/github-metrics.svg) I saw. And here's [the project](https://github.com/wazuh/wazuh) which caused this behavior.

From the webpage, I notice it simply says "view License" on the side bar rather than showing the license name - probably because it's a bespoke license that wasn't recognized:
![image](https://user-images.githubusercontent.com/12629429/122993116-d5313f00-d39e-11eb-9a29-d74a90702d14.png)

Could we perhaps catch these and normalize to 'UNKNOWN' or similar?
If you could point me in the right direction I can probably make a MR, but I'm admittedly not too familiar with JS.

**Comment by aw1cks** [comment]
Taking a look in the [GraphQL API Explorer](https://docs.github.com/en/graphql/overview/explorer):
![image](https://user-images.githubusercontent.com/12629429/122994814-baf86080-d3a0-11eb-8254-c3c21ad16a75.png)

**Comment by lowlighter** [comment]
Hello!

Yes, most of the time when licenses are print, the following is used:
https://github.com/lowlighter/metrics/blob/d59cec98617ae7e9e9c07e7f51364e83ec2e1614/source/templates/classic/partials/stars.ejs#L42

So basically it tries the `nickname` first, if it's null/undefined it fallbacks to `spdxId` and fallback to `name` in last resort.
`name` is avoided because from what I remember output are really long as it's the full name so it's often too verbose and/or cause display issues.

I think the best way to solve this would be to create a formatter for licenses somewhere around here: 
https://github.com/lowlighter/metrics/blob/d59cec98617ae7e9e9c07e7f51364e83ec2e1614/source/app/metrics/utils.mjs#L73

```js
  format.license = function (license) {
    if (license.spdxId === "NOASSERTION")
      return license.name
    return license.nickname ?? license.spdxId ?? license.name
  }
```

And replace occurences from templates (`f` being an alias for `format` functions):
```diff
- <%= repository.licenseInfo.nickname ?? repository.licenseInfo.spdxId ?? repository.licenseInfo.name %> 
+ <%= f.license(repository.licenseInfo) %> 
```

**Comment by aw1cks** [comment]
Thanks! Feel free to assign this to me and I'll give it a go, and get a MR in shortly.
