### ISSUE TITLE
Performance drop

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#414]
Metrics runs have had a consistent large uptick in generation time after July 1 with no change to the settings by me from Jun 27 - Jul 6.

| Run | UTC |
|---|---
| ![image](https://user-images.githubusercontent.com/42429413/125360206-a156a180-e3bf-11eb-8c52-035dfaa26d7f.png) | <br><br><br><br><br><br><br><br><br><br>2 Jul 18:22<br><br><br>1 Jul 18:21<br><br><br><br>30 Jun 23:05<br>(custom run)<br><br><br>30 Jun 18:21 |

**Comment by lowlighter** [comment]
I don't see any changes that could have caused this performance drop 😕

There's a new option `delay` which can be used to make the workflow longer and prevent GitHub rate abuse limit, but it should be off by default.

If it suddenly increased and you use the detailed language feature, it could come from here since it basically clone your repos to compute stats so maybe it could correlate with you recent work?

**Comment by spenserblack** [comment]
```bash
git log --since="June 30 2021" --until="July 2 2021"
```
Only outputs 2 commits (5a15dfd18ef4e980ff974398f28ebe54a8f65c5d and f22a6d613c480e755ba9e330478a3a003b020858), neither of them look like they should cause such a performance drop.
If you use `lowlighter/metrics@698326000340e702ee464d8fafb59ee89fff9cfd` (I've never specified a specific commit for an action before, but I think that's how it's done), do you still experience the performance drop?

**Comment by Nixinova** [comment]
Here's a collection of runs

![Screenshot_20210728-164324](https://user-images.githubusercontent.com/42429413/127265061-3f4e1af2-8611-4ad1-a8b5-5a2deb262e37.png)

Theres definitely a perf drop but it seems to be from 3.9 to 3.10 (3.10 released Jun 1), weird.

**Comment by thib3113** [comment]
Hello, maybe not related, but it seems the dockerFile is always rebuilded ( even using official repo + setting use_prebuilt_image : yes ) .... 

And following the documentation : [Faster execution with prebuilt docker images](https://github.com/lowlighter/metrics/blob/71214a45b5e98d52af015288572085b592850022/source/plugins/core/README.md#-faster-execution-with-prebuilt-docker-images )  
```
already installed dependencies which will cut execution time from ~5 minutes to ~1 minute.
```

So, it can explain this bug ?

**Comment by lowlighter** [comment]
@thib3113 Nice catch 👍 !

It seems the following line doesn't work anymore:
https://github.com/lowlighter/metrics/blob/f9df323fcc9b34eaba3ba01d3a9312b2fe9d425c/source/app/action/action.yml#L58

Because the line which try to extract the action owner doesn't get correctly parsed:
https://github.com/lowlighter/metrics/blob/f9df323fcc9b34eaba3ba01d3a9312b2fe9d425c/source/app/action/action.yml#L44-L46

```
  Source: __lowlighter_
  Version: 3.11.0
  Image tag: v3.11
  Using a forked version
  Image name: metrics:forked-3.11.0
  Image metrics:forked-3.11.0 is not present locally, rebuilding it from Dockerfile
```

For some reason, additional underscores got added but not sure why. 
Since it tries to match my login but it doesn't match, the action thinks it has been forked and is rebuild from scratch from the dockerfile like you said previously

If this is always underscores getting added, maybe we should just add an additional sed to remove them, I don't think they're allowed in GitHub usernames

**Comment by Nixinova** [comment]
I think that is indeed the issue, turning timestamps on, Docker takes 4 min to rebuild:

![image](https://user-images.githubusercontent.com/42429413/127757846-3e6f9268-7a2f-4c06-aeb7-e10c697f5d27.png)

**Comment by Nixinova** [comment]
Yep, that fixed it :+1:

![image](https://user-images.githubusercontent.com/42429413/127760012-e7fbbd77-afc8-47f2-98d5-42f1f4d3be5b.png)
