### ISSUE TITLE
Workflow taking forever to finish (hung)

### ISSUE THREAD

**Issue by simonSlamka** [lowlighter/metrics#419]
Hi,

I just tried to write my .yml based on your example. However, the job seems to be hung. I tried thrice.

![image](https://user-images.githubusercontent.com/51794014/126428072-56f40007-90c7-4f94-b52e-981889936c99.png)

As you can see, it's taking a very long time to finish.

Any idea what could be causing this?

My .yml file
[https://github.com/simonSlamka/simonSlamka/blob/main/.github/workflows/metrics.yml](https://github.com/simonSlamka/simonSlamka/blob/main/.github/workflows/metrics.yml)

Thanks

**Comment by simonSlamka** [comment]
Same thing after trying again, and at the same location: just before the languages plugin.

**Comment by simonSlamka** [comment]
It took a long time to finish, but it's done now.

![image](https://user-images.githubusercontent.com/51794014/126434246-500ea8af-5531-4f42-a38e-e055b4ed5a74.png)

Closing.

**Comment by lowlighter** [comment]
The `languages` plugin in detailed mode can be really long because of how it works

It actually clones repositories you worked on and walk through git logs to find your commits and count the bytes you added using git patches 🙂 

Stats should be more accurate than using non detailed mode, but it's a bit longer

**Comment by simonSlamka** [comment]
Ah, okay. Makes perfect sense. Thanks!
