### ISSUE TITLE
Mismatch between Inspirationer text and value

### ISSUE THREAD

**Issue by spenserblack** [lowlighter/metrics#447]
The text says "Maintaining a repository which has been forked `x` times".
But, at a quick glance, it seems like `x` is the most forks of a repository that the user *owns*, and doesn't include repositories that the user maintains but *does not own*. In other words, I don't think that repositories where the user is a collaborator are counted.

So I think there's 2 possible solutions

1. Change "Maintaining" to "Owning", "Owns", or something like that
2. Change the calculation to include repos they collaborate on

1 is probably better, since I assume being an "Inspirationer" means *creating* something that others want to fork,
which a collaborator is less likely to be than an owner.

On a side note, I don't think "Inspirationer" is a real word (but it sounds cool!) :laughing:

**Comment by lowlighter** [comment]
I think it's because the achievements plugin doesn't fetch repositories again to save queries, so it uses those gathered by the base/core plugins instead. It means that it's also affected by `repositories_affiliations` (which default to `OWNER`) so depending on this setting, the text could be true or indeed misleading.

So 1 is probably the way to go, but if the user change the affiliations it could be misleading too since they may not own it too 😕 
Either we need to find a wording that could match both, or change it dynamically based on the setting but the latter seems hacky.

> On a side note, I don't think "Inspirationer" is a real word (but it sounds cool!) 😆

Yes it's possible 🤣 
This is mostly because I was searching for single words finishing in `-er` to keep consistant with other achievements. Also, since the prefix (`master`/`super`/`great`/``) is automatically added, it makes it a bit harder to find something that sounds good without being weird. If you can come up with a better wording we can change it 😆

**Comment by spenserblack** [comment]
I see, I wasn't aware that the same data as the base/core plugins was used for achievements. It seems like some achievements don't use that data, though, but use data queried just for the achievements plugin, like "maintainer". I need to learn about GraphQL, but would it count as an additional query if you add another field to the `achievements.graphql`? Is there a possible query for getting the most forked repo that the user owns?
Otherwise, going with 1, could the repo data be iterated through and filtered to only repos that the user owns, regardless of the setting of `repositories_affiliations`?
I'll dig into the code some more (I should have done this earlier :sweat_smile: )

***

>If you can come up with a better wording

Personally I do like "Inspirationer". but here are a couple of words that Merriam-Webster seems to recognize:
- [Inspirer](https://www.merriam-webster.com/thesaurus/inspirer) (my spell check doesn't recognize this, though)
- Originator (because they created the original version)

**Comment by lowlighter** [comment]
> I see, I wasn't aware that the same data as the base/core plugins was used for achievements. It seems like some achievements don't use that data, though, but use data queried just for the achievements plugin, like "maintainer"

Yes, usually it's preferable to avoid dependencies between plugins so they're independant, but

**Comment by spenserblack** [comment]
>I think either we keep "Inspirationer" or switch to "Inspirer".

Well, I suppose "Inspirer" is best, since it's "more correct" (but it still isn't recognized by spellcheck, so it's not a reasonably common word).

Your native language is French, right? (I'm guessing this because of your spelling of "categorie" :laughing: ). How would you have said "Inspirationer" in your language? Finding the different translations for the French word might help find a good English word.

**Comment by lowlighter** [comment]
> Is your native language French? (I'm guessing this because of your spelling of "categorie" 😆 ). How would you have said "Inspirationer" in your language? Finding the different translations for the French word might help find a good English word.

Yes indeed 🤣 
It's hard to fix some typing habits, especially since the word is similar is both languages and the plural form is the same. I got the same issue with punctuation, spaces often get added before "?" and "!" 

I guess I would have say "Inspirateur" (probably why I ended up with "Inspirationer") but it actually translate the same as you suggested:
<img src="https://user-images.githubusercontent.com/22963968/128243831-d347dcc1-3302-4e57-9e54-04eedbb3bfe0.png" width="360">

So I guess we should go with "Inspirer" 👍

**Comment by spenserblack** [comment]
I looked up "inspirator" after seeing "inspirateur", and [it looks like it's a recognized word for Merriam-Webster](https://www.merriam-webster.com/dictionary/inspirator). "Inspirer" sounds more modern than "inspirator" to me, personally, though.

**Comment by lowlighter** [comment]
Yeah "inspirer" is good
