### ISSUE TITLE
SVG is broken at bottom.

### ISSUE THREAD

**Issue by nathan130200** [lowlighter/metrics#506]
After some days, when metrics action execute, produces an SVG with bottom broken.
![image](https://user-images.githubusercontent.com/14365254/131221259-eb3fdc5b-1043-4d09-b510-0f03e60e5595.png)
For example in Wakatime status, the image crops OS usage. I reduced starred repositories (from 5 to 4) to check if solves, but same happened.

**Comment by lowlighter** [comment]
You can use `config_padding` option to increase the final height (try a higher percentage in your case):

https://github.com/lowlighter/metrics/blob/e3cd805fa480071232fd4bff35565251bafaf263/source/plugins/core/metadata.yml#L186-L192

Partially related to #321. Unfortunately resizing SVG is not that simple because the rendering is not the same depending on operating systems, browser and environements, which may use different fonts or fonts size or not use the same rendering engine to display svgs

**Comment by nathan130200** [comment]
Oh thanks!
