### ISSUE TITLE
Innaccuracies with language plugins stats

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#531]
While investigating on #513 I noticed some flaws in the languages plugin.

It is actually not very well defined whether it should count your effective language stats (meaning stats from the current state of each repo) or cumulative language stats (meaning stats should include previous state of each repo, including code that has been refactored, moved or deleted).

Currently, the languages indepth analyzers is doing the following:
1. Clone locally repository
2. Call linguist on it
3. `git log --patch` on each user commit to find which lines were added by user and update bytes count using detected language by linguist
4. Remove locally cloned repository

For now, it leans more toward cumulative stats rather effective stats.
Since tracking deleted files is currently impossible because they don't exist when linguist analyze the repository (so detected language for a deleted file is always `null`), deleted/moved files are never taken into account so some lines are actually lost

Also renamed file may be counted multiple times, need to check whether an option exists to detect them (maybe `--follow`?)

**Comment by Nixinova** [comment]
Other issues:
- I have a repo with some raku https://GitHub.com/nixinova/dynaver but it doesn't show up in my stats
- I added some lines of ruby to https://github.com/GitHub/linguist and it only showed up when my fork was existent; the commit on GitHub/linguist isn't checked for language data

**Comment by Napolitain** [comment]
Hey,

I have inaccuracies in the depth stats, as we can guess from this image.
<img width="471" alt="Capture d’écran 2021-09-26 à 19 12 07" src="https://user-images.githubusercontent.com/18146363/134818763-2190b3fd-b621-4444-883a-d27cd6be8445.png">

Out of 1155 commits, plugin looks at only 186. My token has those rights.
<img width="641" alt="Capture d’écran 2021-09-26 à 19 57 29" src="https://user-images.githubusercontent.com/18146363/134818811-d744f369-731d-4176-bcba-932fac2963bd.png">

Normally, it should show much more C# than it does at the moment. I don't think the token is lacking (even tho I suspect it is could be a token issue since I use organizations and private repositories a lot for school).

What do you think?

**Comment by Napolitain** [comment]
@lowlighter I have tried regenerating token before I saw your response, which turned out to be an error (it logs less total commits), then tried your suggestion. It is clearly better, but still lacking commits.
<img width="476" alt="Capture d’écran 2021-09-28 à 11 58 07" src="https://user-images.githubusercontent.com/18146363/135066823-84d0f939-56e6-49b8-b0a8-86a7ec043901.png">

Now I'm at 345 commits analyzed of 955 total. 
Should the plugin_indepth parameter asks metrics to look at all commits ever ? Or it has a limit behind the hoods ?

**Comment by Napolitain** [comment]
Ok so I removed "indepth" and it seems better representative of the repositories.

I think that's linked to what you describe in this issue, as it shows only current state. And I think it reads the last commit of each file (or something like that) so only few lines are registered (and not the whole file).
A typo fix would then count as 1 line for a whole file.

**Comment by lowlighter** [comment]
Superseded by #857
