### ISSUE TITLE
Display mode "columns" only renders a single column

### ISSUE THREAD

**Issue by oSumAtrIX** [lowlighter/metrics#542]
I have set up the [workflow ](https://github.com/oSumAtrIX/oSumAtrIX/blob/main/.github/workflows/metrics.yml)in [my github repository](https://github.com/oSumAtrIX/oSumAtrIX)  to use the `columns` display mode, but it renders out a single column image on desktop. Additionally there is a height issue with the page speed insight plugin.

**Here is a preview of the last workflow:**
![Metrics image](https://raw.githubusercontent.com/oSumAtrIX/oSumAtrIX/ce73a60e6113c59082ec1235fddf1c7152217a3f/github-metrics.svg)

**Comment by lowlighter** [comment]
Hello! 
When using this mode, you need to use the html tag with width attribute rather than the markdown one, like:
```html
<img src="https://github.com/my-github-user/my-github-user/blob/master/github-metrics.svg" alt="Metrics" width="100%">
```
There is an open issue for height/ration (#374), but unfortunately with no solution yet 😕 

____

<img src="https://raw.githubusercontent.com/oSumAtrIX/oSumAtrIX/ce73a60e6113c59082ec1235fddf1c7152217a3f/github-metrics.svg" width="100%">

**Comment by oSumAtrIX** [comment]
Thank you, it was mentioned [here](https://github.com/lowlighter/metrics#4-embed-link-into-your-readmemd).
