### ISSUE TITLE
URL parameters do nothing

### ISSUE THREAD

**Issue by Nixinova** [lowlighter/metrics#60]
On the metrics website, changing the URL parameters of a rendered image do not affect it at all. For instance, https://metrics.lecoq.io/Nixinova always shows the same image no matter what URL params (if any) you put. The only way to change the content of the image is to go back to the homepage and re-render the image. Is this intended?

**Comment by lowlighter** [comment]
Hello !

Yes, there is actually a cache of one hour on the web instance, mostly to save time and resources (as generation take a few seconds depending on enabled plugins, and also to avoid hitting GitHub's own rate limit). 

When rendering through the website, it'll flush cache before so that's why changes are immediate.

**Comment by Nixinova** [comment]
Alright, thanks for answering. Good to know that the parameters will eventually work and I don't need to go to the homepage every time.
