### ISSUE TITLE
Highlight some details differently

### ISSUE THREAD

**Issue by p00f** [lowlighter/metrics#66]
It would be nice if these were highlighted differently to stand out
![image](https://user-images.githubusercontent.com/36493671/104833633-0c676580-58c0-11eb-8058-3f78f44a0b00.png)

**Comment by lowlighter** [comment]
Hello !

I'm not sure what you mean by highlighted differently. You mean something like a different color or like their own section ?

**Comment by p00f** [comment]
I was thinking of a different colour

**Comment by lowlighter** [comment]
I don't think it'll be changed in official releases since it's been a long time like this and I don't want to suddenly change everyone's metrics, but you can achieve what you want pretty easily if you don't mind making a fork and tweak some stuff (~5 min). 

Basically, metrics is just html/css (with a bit of [EJS](https://github.com/mde/ejs)), so you just need to :
- patch [templates/classic/style.css](https://github.com/lowlighter/metrics/blob/master/source/templates/classic/style.css) with a new css class
  - for example `.highlight { color: red; font-weight: bold }`
- patch [templates/classic/partials/base.repositories.ejs](https://github.com/lowlighter/metrics/blob/master/source/templates/classic/partials/base.repositories.ejs#L40-L67) and [templates/classic/partials/base.header.ejs](https://github.com/lowlighter/metrics/blob/master/source/templates/classic/partials/base.header.ejs#L18-L21) and append your new css class to what you want to highlight :
  - https://github.com/lowlighter/metrics/blob/c34e73fa6867b069526fe90a626adcc02e63854f/source/templates/classic/partials/base.header.ejs#L18-L21
  - for example, you would replace `<div class="field">` by `<div class="field highlight">`
- finally change your workflow to your fork instead of `lowlighter/metrics@latest`
  - for example  `uses: p00f/metrics@master` 

Hope this helps 👍

**Comment by p00f** [comment]
Thanks!

**Comment by lowlighter** [comment]
You're welcome!

**Comment by p00f** [comment]
@lowlighter it isn't working, i tried both `.highlight { color: pink; font-weight: bold; }` and `.font.highlight { color: pink; font-weight: bold ;}` in `style.css`

**Comment by lowlighter** [comment]
Hello !

Could you try changing `- uses: p00f/metrics@latest` by `- uses: p00f/metrics@master` in your workflow ? 

`@latest` doesn't take account of your commits, so that's probably why you're not seing any changes, but `@master` do 🙂 

By the way, below is a render of what it'll look like: 
![image](https://raw.githubusercontent.com/lowlighter/debug-metrics/master/customized.svg)

**Comment by p00f** [comment]
oof totally forgot about that. it works now
