### ISSUE TITLE
Customization on Terminal template

### ISSUE THREAD

**Issue by rafifos** [lowlighter/metrics#67]
This could (maybe) be superseeded by https://github.com/lowlighter/metrics/projects/1#card-52983221 but it would be nice if we could customize some options for the terminal plugin, like the `background-color`, `font-family` or even override the entire css.

**Comment by lowlighter** [comment]
Hello ! 

It is actually possible to achieve what you want by forking this repository and updating [source/templates/terminal](https://github.com/lowlighter/metrics/tree/master/source/templates/terminal) files. 

You can then edit [style.css](https://github.com/lowlighter/metrics/blob/master/source/templates/terminal/style.css) to add custom css, or even totally rewrite it if you want. For [fonts.css](https://github.com/lowlighter/metrics/blob/master/source/templates/terminal/fonts.css), it's a bit trickier since fonts must be base64 encoded (you can follow this [section](https://github.com/lowlighter/metrics/blob/master/CONTRIBUTING.md#-fonts) for instructions) but it still remains easy. You can also edit [partials](https://github.com/lowlighter/metrics/tree/master/source/templates/terminal/partials) to change  displayed content (though for `terminal` template, it's a bit hard to read because of preserverd white-space).

Once you're done, just change your workflow file to use your fork instead of `lowlighter/metrics@latest` (e.g. `rafifos/metrics@master`). 

Docker image from forked repositories are always rebuilt from scratch from the [Dockerfile](https://github.com/lowlighter/metrics/blob/master/Dockerfile), so if you're targetting your `@master` branch, it'll always have your latest changes (only drawback is that it'll take ~5min instead of ~1 min).

____

With #68, you'll be able to use metrics with anyone's custom template. It's not that useful if you own the fork, but others users will be able to use your custom terminal metrics using :
```yaml
- uses: lowlighter/metrics@master
  with:
    # ... other options
    template: "@terminal"
    setup_community_templates: rafifos/metrics@master:template+trust
```

____

Hope this helps 🙂

**Comment by lowlighter** [comment]
Also to add on previous answer, I don't plan on integrating options to customize templates as I believe forking and directly editing source files is actually easier and better for users 🙂

Hope this makes sense 👍

**Comment by rafifos** [comment]
Looks good to me, it's not that difficult to fork it and modify anyway.
