### ISSUE TITLE
Bug? metrics gets cut off

### ISSUE THREAD

**Issue by ProFireDev** [lowlighter/metrics#796]
### Discussed in https://github.com/lowlighter/metrics/discussions/795

<div type='discussions-op-text'>

<sup>Originally posted by **ProFireDev** January 20, 2022</sup>
![image](https://user-images.githubusercontent.com/34112557/150399628-2ec4f71f-951b-492d-ae2e-5a837af18d9f.png)

^the bottom text is pushed off the svg on my profile. My config and the svg are attached below in the zip
[ProFireDev-main.zip](https://github.com/lowlighter/metrics/files/7907673/ProFireDev-main.zip)
</div>

**Comment by lowlighter** [comment]
Hi!

Yes this is a known issue (it's more or less the same issues as #321) unfortunately it's not fixable easily because the rendering depending on OS/browser/fonts combination and it may actually render differently between platforms

However there you should be able to fix it by configuring [`config_padding`](https://github.com/lowlighter/metrics/tree/master/source/plugins/core#-adjusting-padding) 👍

**Comment by ProFireDev** [comment]
thankyou!
