### ISSUE TITLE
Known issue: `config_display: columns` bad dimensions 

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#839]
When [`config_display`](https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#%EF%B8%8F-controlling-display-size) option is set to `columns`, it uses [CSS @media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) to adjust width dynamically.
However, since height needs to be fixed by the viewbox and height of the SVG, dynamic height resizing is hard (impossible?) to achieve (see #374).

Current workaround is to manually split the image by using multiples jobs, and use `<img align="{left|right|center}">` to embed metrics.

If you know how to fix it, feel free to open an issue or comment

**Comment by JayantGoel001** [comment]
Hello @lowlighter,

Regarding the height issue and config_display, I think instead of **directly** creating SVG file, we should create **HTML** code and convert that **HTML code to SVG.** 🤔

Metrics generated in the case of @Zenoo was https://raw.githubusercontent.com/Zenoo/zenoo/f0eb3da9562b73352d8cb69c310e4b0dcca35938/github-metrics.svg

I created corresponding code in HTML of the same with few changes and I put 
https://codeshare.io/bvpngM

and Now using this website 
https://www.hiqpdf.com/demo/ConvertHtmlToSvg.aspx
I converted HTML code to SVG.

![HtmlToSvg](https://user-images.githubusercontent.com/54479676/152575264-4773dc15-fac0-4020-93e4-e6196b73fb02.svg)
This is the final output of SVG though the second column seems inappropriate yet the height issue is fixed.

**Comment by lowlighter** [comment]
Actually a similar system is already used: it renders the svg in an html page, compute bounding rect and crop it (btw this is also why the size may differ in the end because it's rendered on ubuntu+chrome+system fonts which may not have same height on other environment).

The "height oversize" is actually intentional for now. This mode implies "2 heights": one for 2 columns, one for 1 column.
However, just using the height for a single column would just look cropped on smaller displays (because when the media query triggers, the viewbox won't be updated) 😕

Note that it only happens when embed in an `<img>` tag, when viewing raw svg or in a html file it renders fine
