### ISSUE TITLE
YouTube plugin

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#96]
I'm happy to make a plugin that displays recently posted videos for YouTube channels, if people like this idea I'll PR it

**Comment by lowlighter** [comment]
It seems a good addition!
I don't know the possibilities of Youtube API but it would be cool to display at least thumbnails along with title, description, date  and views/likes 🙂

If you're really interested in implementing it, you can check details below:
<details>
<summary>tldr; making a new plugin</summary>

Since #82, it's easier to create new plugins (though it still requires a bit of work). 
Here's the minimal setup for a plugin (you can use `npm run quickstart -- plugin youtube` for a head start):
- A new folder in `plugins/` with at least:
  - `index.mjs` (code)
  - `metadata.yml` (description and inputs)
  - `README.md` (documentation)
  - `tests.yml` (unit tests)
- In supported templates:
  - plugin name to `partials/_.json`
  - a new `.ejs` file (plugin render)
- Mocked data [`app/mocks/api`](https://github.com/lowlighter/metrics/tree/master/source/app/mocks/api/axios) for external APIs
- Mocked result for [app.placeholder.js](https://github.com/lowlighter/metrics/blob/master/source/app/web/statics/app.placeholder.js) (optional, but it allows web instance to render a placeholder)

For testing locally and quickly, the best is to setup a web instance (`npm install`, configure `settings.json` and run `npm start`).
Use 1260px width images for documentation if needed.

There's no need to patch README.md, action.yml, settings.example.yml, source/plugins/README.md and source/templates/README.md as these are now rebuilt automatically.

[contributing.md](https://github.com/lowlighter/metrics/blob/master/CONTRIBUTING.md#-extending-metrics) explains additional stuff, but just looking at other plugins should be enough to understand how metrics works. You can also checkout #90  as PR example, though it's not perfect.

If the above didn't discourage you and you want to give it a shot, please go ahead 🙂 !

</details>

**Comment by Milo123459** [comment]
Thanks!! I have some cool ideas such as recently uploaded videos, subscribers, cumulative views and stats on a specific video.

**Comment by Milo123459** [comment]
I'll reopen this later
