### ISSUE TITLE
Cropping issue

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#98]
http://i.fionn.live/76763f.png

**Comment by lowlighter** [comment]
Yeah it may be possible that rendered images are cropped from time to time because SVG renders differently based on OS/browser/environment 😕

You can [adjust padding](https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#-adjust-padding) manually to mitigate this issue if needed 👍

**Comment by Milo123459** [comment]
Got it, thanks

**Comment by Milo123459** [comment]
@lowlighter a suggestion is just making the svg bigger then it has to be?

**Comment by lowlighter** [comment]
Yeah maybe default `config_padding` should be higher, but it's pretty hard to adjust it, #33 shows what's increasing SVG size too much will produce. But maybe 8-10% would be better than 6%

It's really hard to find the right compromise because each browser/os really have their own rendering (as it's essentially HTML/CSS), I even sometimes get display issues because Safari is so much behind other browsers like Firefox or Chrome that it's displaying flex box weirdly. 

An attempt I made was to provide embedded fonts for the classic template, but it looked really odd because the rest of webpage was using system fonts (which are different across OS) so it didn't fit, plus it was significantly increasing produced metrics file size.

At least it's better now that when metrics was using static formulas 😅

**Comment by Milo123459** [comment]
![](http://i.fionn.live/709430.png])

**Comment by Milo123459** [comment]
same issue, i have an idea however.

**Comment by Milo123459** [comment]
changing padding doesnt fix

**Comment by lowlighter** [comment]
I'm not remembering whether you had problems with cropped bottom, or just cropped parts inside the SVG (image from first comment is gone) 😅 

If that's the latter, it may be a CSS issue instead. Maybe tweaking line-height or div height may solve the problem

**Comment by Milo123459** [comment]
This is now cutting stuff off at the bottom. So yes, cropped @lowlighter

**Comment by Milo123459** [comment]
P.S check my profile for an example, scroll down to the bottom

**Comment by lowlighter** [comment]
[This](https://github.com/Milo123459/Milo123459/blob/master/.github/workflows/metrics.yml#L19) may not be sufficient, maybe try to use something like `10%, 30%` (it's `width, height` format) or an even-higher value for height.

Also, changes on profile page may not be instantaneous (as images are cached by GitHub). Checking directly your [github-metrics.svg](https://github.com/Milo123459/Milo123459/blob/master/github-metrics.svg) (or its raw version) may actually display a different result which is the real render (and seems to be fine, at least from my side)

**Comment by Milo123459** [comment]
I've done both of those and unfortunately, this error persists. How would we fix it?

**Comment by lowlighter** [comment]
I need to think a bit about it, I'll check it tomorrow

**Comment by lowlighter** [comment]
Patch probably needs to be done somewhere here:
https://github.com/lowlighter/metrics/blob/882a93dea59f7e850ab038218849838f81061373/source/app/metrics/utils.mjs#L118-L138
Maybe puppeteer `load` event is not enough but I'm not sure other options would solve it, as `networkidle0` and `networkidle0` won't change anything since metrics don't use any external content (images are all base64 encoded).
It would explain why boundingRect is incorrectly reporting size.

Best would probably to debug without headless mode and on a ubuntu system (same environment as GitHub action) check behaviour of `#metrics-end` tag.

But yeah unfortunately I don't see any other solution for now 😕

**Comment by Milo123459** [comment]
Sad, I do think this is somewhat high priority

**Comment by lowlighter** [comment]
Yeah, I'll try to find a solution to patch it quickly

**Comment by Milo123459** [comment]
Changes title as it makes more sense. See my profile for an example.

**Comment by Milo123459** [comment]
So this is fixed in the v3.4 release, right?

**Comment by lowlighter** [comment]
Not sure, that's why I didn't link it to v3.4
But hopefully it'll be a bit better

**Comment by Milo123459** [comment]
Woooohooo! Fixed 🗡️
