### ISSUE TITLE
Spotify recently played doesn't "update"

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#99]
I mean it runs every hour and I've listened to other songs and it isn't updating on the svg. Ideas?

**Comment by lowlighter** [comment]
I'll investigate 👍 
I may have some leads about it

**Comment by Milo123459** [comment]
That's great, I believe it has something to do with refresh tokens.

**Comment by Milo123459** [comment]
![](http://i.fionn.live/d61ab4.png) it has changed, it's just that i played these songs like 14 hours ago

**Comment by lowlighter** [comment]
I've still not finished fixing it, but I think that's because the Spotify API query is set to get songs recently played 24 hours ago, but maybe it'll be better to "reversly iterating" over recent time (like 1, 2, 3, ... hours ago) to get a more accurate list.

Plus I'm seeing that you've got duplicates in your render, I'll also look to make it display only once 🙂

**Comment by lowlighter** [comment]
Should be better with bugfix introduced in #107
